# Generated by Django 4.2.1 on 2023-07-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст')),
                ('search_content', models.TextField(verbose_name='Текст для поиска')),
                ('search_title', models.TextField(db_index=True, max_length=255, verbose_name='Заголовок для поиска')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
                'db_table': 'app_note_note',
            },
        ),
    ]
