# Generated by Django 4.2.1 on 2023-08-20 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст')),
                ('search_content', models.TextField(verbose_name='Текст для поиска')),
                ('search_title', models.TextField(db_index=True, max_length=255, verbose_name='Заголовок для поиска')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
                'db_table': 'app_note_note',
            },
        ),
        migrations.CreateModel(
            name='NoteStorageServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('Firestore', 'Firestore'), ('Typesense', 'Typesense'), ('DjangoServer', 'Микросервис заметок'), ('Github', 'Github')], max_length=30, verbose_name='Внешний сервис базы')),
                ('credentials', models.JSONField(default=dict, verbose_name='Данные для полключения')),
                ('description', models.CharField(default='', max_length=100, verbose_name='Комментарий')),
                ('is_default', models.BooleanField(default=False, help_text='Если да, то эта база будет использовано при открытии страницы списка заметок, а также при редактировании заметки', verbose_name='Является ли база по-умолчанию?')),
                ('source', models.CharField(db_index=True, help_text='Используется для указания базы при поиске, редактировании и отображении заметок', max_length=30, unique=True, verbose_name='Уникальный идентификатор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'База заметок',
                'verbose_name_plural': 'Базы заметок',
            },
        ),
    ]
