# Generated by Django 4.2.1 on 2023-07-15 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteStorageServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=30, verbose_name='Внешний сервис хранилища')),
                ('credentials', models.JSONField(default=dict, verbose_name='Данные для полключения')),
                ('description', models.CharField(default='', max_length=100, verbose_name='Комментарий')),
                ('is_default', models.BooleanField(default=False, help_text='Если да, то это хранилище будет использовано при открытии страницы списка заметок, а также при редактировании заметки', verbose_name='Является ли хранилищем по-умолчанию?')),
                ('source', models.CharField(db_index=True, help_text='Используется для указания хранилища при поиске, редактировании и отображении заметок', max_length=30, unique=True, verbose_name='Уникальный идентификатор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Хранилище заметок',
                'verbose_name_plural': 'Хранилища заметок',
            },
        ),
    ]
