# Generated by Django 4.2.1 on 2023-08-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='path',
            field=models.CharField(db_index=True, default='default', max_length=10, verbose_name='Путь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(fields=('path', 'title'), name='unique_note'),
        ),
    ]
