# Generated by Django 4.2.1 on 2023-09-03 14:10
import uuid

from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    NoteStorageServiceModel = apps.get_model("note", "NoteStorageServiceModel")
    for row in NoteStorageServiceModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

    Note = apps.get_model("note", "Note")
    for storage in NoteStorageServiceModel.objects.filter(service='DjangoServer'):
        Note.objects.filter(path=storage.credentials['path']).update(storage_uuid=storage.uuid)
        storage.credentials = {}
        storage.save()


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_note_path_alter_note_title_note_unique_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='storage_uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='notestorageservicemodel',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
