# Generated by Django 4.2.1 on 2023-09-03 14:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_note_storage_uuid_notestorageservicemodel_uuid'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='note',
            name='unique_note',
        ),
        migrations.AlterField(
            model_name='note',
            name='storage_uuid',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='notestorageservicemodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['storage_uuid'], name='index_storage_uuid_note'),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(fields=('storage_uuid', 'title'), name='unique_note'),
        ),
    ]
