# Generated by Django 4.2.1 on 2023-09-03 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_remove_note_unique_note_alter_note_storage_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='path',
        ),
    ]
