# Generated by Django 4.2.1 on 2023-09-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0007_alter_note_storage'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='note',
            name='unique_note',
        ),
        migrations.RemoveIndex(
            model_name='note',
            name='index_storage_uuid_note',
        ),
        migrations.AlterField(
            model_name='imagenote',
            name='image',
            field=models.ImageField(upload_to='note'),
        ),
        migrations.AlterField(
            model_name='note',
            name='storage_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notestorageservicemodel',
            name='credentials',
            field=models.JSONField(default=dict, verbose_name='Данные для подключения'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['storage'], name='index_note_storage'),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(fields=('storage', 'title'), name='unique_note_storage_title'),
        ),
    ]
