# Generated by Django 4.2.1 on 2023-09-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0008_remove_note_unique_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='storage_uuid',
        ),
    ]
