# Generated by Django 4.2.1 on 2023-10-14 02:33

from django.db import migrations, models
import note.validators


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0010_note_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='search_title',
            field=models.TextField(db_index=True, max_length=240, verbose_name='Заголовок для поиска'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(db_index=True, max_length=240, validators=[note.validators.FilenameValidator()], verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='notestorageservicemodel',
            name='source',
            field=models.CharField(db_index=True, help_text='Используется для указания базы при поиске, редактировании и отображении заметок', max_length=30, unique=True, validators=[note.validators.FilenameValidator()], verbose_name='Уникальный идентификатор'),
        ),
    ]
