# Objects' lifecycle

BEFORE_CREATE_GETTING_ADAPTER = 1
BEFORE_CREATE = 2
CREATED = 3
BEFORE_UPDATE_GETTING_ADAPTER = 4
BEFORE_UPDATE = 5
UPDATED = 6
BEFORE_DELETE_GETTING_ADAPTER = 10
BEFORE_DELETE = 11
DELETED = 12
BEFORE_OPEN_CREATE_PAGE = 13
BEFORE_OPEN_VIEW_PAGE = 14

# Context of objects' lifecycle

WEB = 1
API = 2
